### PR TITLE
MODULES-6599 - Make MOTD compatible with FreeBSD

### PR DESCRIPTION
**Pull request by Q1tum**
MODULES-6599 - Support FreeBSD for puppet module MOTD

### CODE REVIEW

**Comment by smortex** [comment]
Nice! Shouldn't `/etc/issue` and `/etc/issue.net` be skipped on FreeBSD?

**Comment by Q1tum** [comment]
@smortex thanks for the suggestion, I updated this pull request.

**Comment by pmcmaw** [comment]
Hey @Q1tum,
Nice work, however we are happy enough to make the module compatible with FreeBSD although we are not prepared to support this configuration. If you remove the entries from the metadata.json I will get this PR merged. Again please be aware FreeBSD will be **compatible**, not **supported**.

**Comment by Q1tum** [comment]
Hi @pmcmaw 

The metadata has been updated as requested, the main goal for me was to be able to use the module on FreeBSD in a project I'm working on, so **compatible** instead of **supported** is fine by me.

**Comment by pmcmaw** [comment]
This has ran through our internal CI with no issues. Squash and merging.

**Pull request merged**
