### PR TITLE
(MODULES-7069) Add compatibility for AIX

### PR DESCRIPTION
**Pull request by jarretlavallee**
This PR adds support for AIX to specify a `/etc/motd`, `/etc/issue` and `/etc/issue.net`.

### CODE REVIEW

**Comment by jarretlavallee** [comment]
Fixed the release_checks deprecation issue with the spec tests. Do you want me to update this to PDK 1.5.0?

**Comment by pmcmaw** [comment]
Hey @jarretlavallee 

I just want to thank you for taking your time to submit this PR. We will be running a `pdk update` soon for pdk 1.5.0 so your temporary fix for release_checks is perfect.

If you could remove the AIX entries from the `metadata.json` I will get your PR merged. 

When merging this PR I would like to make you aware this will make the code base `compatible` with the module, however Puppet will not `support` this operating system. By support I mean we will not be running tests against this OS or providing bug fixes specific to this OS. I would like to make sure you are ok with this before I merge. 👍

**Comment by jarretlavallee** [comment]
@pmcmaw Thanks for taking the time to review this! I removed the updates to the `metadata.json` as I am perfectly fine without the AIX system tests. Thanks!

**Comment by pmcmaw** [comment]
@jarretlavallee thank you for this! 👍

**Pull request merged**
