### PR TITLE
(maint) Convert module for PDK Compatibility

### PR DESCRIPTION
**Pull request by bmjen**

### CODE REVIEW

**Comment by willmeek** [comment]
Looks good, but is there a way of ignoring modulesync files?
(These usually begin with "#This file is generated by ModuleSync, do not edit." or otherwise live / templated at https://github.com/puppetlabs/modulesync_configs ) :)

These would be overwritten anyway on the next modulesync.

- .gitignore
- .rubocop.yml
- .travis.yml
- Gemfile
- Rakefile
- appveyor.yml

**Comment by bmjen** [comment]
Unfortunately, we don't have the capability of ignoring files at the moment. That's definitely something we'll have to add to the convert feature.

**Comment by bmjen** [comment]
@willmeek also, with this module being converted now, we may think about removing it from the modulesync managed modules, and making PRs to pdk-templates when changes are needed/wanted.

**Comment by HelenCampbell** [comment]
PR to Remove motd from modulesync - https://github.com/puppetlabs/modulesync_configs/pull/172

**Pull request merged**
